-- EI-OS Auto-Remediation Migration
-- Root cause: The documents endpoint is still returning full document sets instead of using the newly added pagination, causing excessive processing time and higher compute cost.
-- Fix: Enable the pagination parameters (cursor/limit) in production and update client calls to request limited pages, or roll out the PR changes to the live service.
-- Generated by Enterprise Intelligence OS

CREATE INDEX IF NOT EXISTS idx_users_activity
    ON users_activity(user_id, created_at DESC);

COMMENT ON INDEX idx_users_activity IS
    'EI-OS auto-fix: composite index to prevent sequential scans';
